### ISSUE TITLE
Fix Header

### ISSUE THREAD

**Issue by cecilsmith** [joshua-smith/23-24-FTC#2]
https://github.com/18018-Micro/CenterStage-2023-24-Code/blob/af6c25df16b26dd349473badfabbf07ef02a1010/TeamCode/src/main/java/org/firstinspires/ftc/teamcode/MainTeleOp.java#L1

The header should accurately reflect your current team name. Not the old one. ;)

**Comment by joshua-smith** [comment]
Oops :). Good spot!
